### ISSUE TITLE
Rolemap Guide?

### ISSUE THREAD

**Issue by senadventure** [Sonoran-Software/SonoranBot-Documentation#1]
Where do you find the rolemap guide for the Sonoran Bot and linking discord roles to permissions within the CAD?

There used to be a page where you could select the permissions you would like members to have and it would generate a code for you to use with your discord role linking. Is this not a thing anymore?

Specifically I am looking for the "Role Mask" id generator.

**Comment by Fireant456** [comment]
This is not a development issue and support questions can be directed to our [support team](https://support.sonoransoftware.com)

**Comment by senadventure** [comment]
It used to be listed on github and within these repositories, but is no longer here. Is there not a way to access this anymore, or are you just too incompetent to answer my question...?

**Comment by Fireant456** [comment]
@senadventure we do not take kindly to insults against our team and staff. If you had followed my advice you would have been able to get your question answered within a few minutes and been informed that link is provided to you by the bot when running the /rolemap command at the time of setting up the bot.

Have a good rest of your day. Please respect me and all of my other colleagues by speaking respectfully to us, not insulting us for doing our jobs and following directions to submit inquiries to the proper channels. Incorrect usage of our services will result in termination of services and being banned from doing future business with us per our Terms of Service.
